os: linux
dist: bionic
sudo: required
language: python
python:
  - "3.7"
git:
  depth: 1
before_script:
  - sudo apt-get install ffmpeg
  - pip install -r requirements.txt

branches:
  only:
  - master

script:
  - git config --global user.email "travis@edyo.es"
  - git config --global user.name "Travis for EDyO"

#  - git clone https://github.com/dacacioa/pydub.git ../pydub
#  - ln -s ../pydub/pydub/ pydub

  - git checkout -b travis_ci
  - python ./appu.py
  - git status
  - git add -A
  - git status
  - git commit -am "Pushing podcast from travis..."
  - git push "https://${GH_TOKEN}@github.com/EDyO/appu.git" -f
