os: linux
dist: xenial
language: python
python:
  - "2.7"
sudo: required
before_script:
  - export PATH="$HOME/node_modules/.bin:$PATH"
  - sudo apt-get install libav-tools 
script:
  - git config --global user.email "travis@edyo.es"
  - git config --global user.name "Travis for EDyO"
  - git clone https://github.com/dacacioa/pydub.git ../pydub
  - ln -s ../pydub/pydub/ pydub
  - git checkout master
  - python ./aae.py 
  - git add -A
  - git commit -am "Pushing podcast from travis..."
  - git push "https://${GH_TOKEN}@github.com/dacacioa/AAE.git" -f
