on:
  push:
    tags:
      - "*"
permissions:
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag name
        id: tag_name
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> ${GITHUB_OUTPUT}
      - name: Build and publish Docker image
        run: |
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u EDyO --password-stdin
          docker build --pull --rm -f "appu/Dockerfile" -t ghcr.io/edyo/appu:${{ steps.vars.outputs.tag }} appu/.
          docker push ghcr.io/edyo/appu:${{ steps.vars.outputs.tag }}
  release:
    needs:
      - docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        destination_os: [linux, windows, darwin]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Tidy dependencies to local
        run: |
          go mod tidy
      - name: Build
        run: |
          scripts/build.sh ${{ matrix.destination_os }} amd64
      - name: Get tag name
        id: tag_name
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> ${GITHUB_OUTPUT}
      - name: Release built binaries
        run: |
          echo ${{ secrets.TEST_TOKEN }} | gh auth login --with-token
          gh release upload ${{ steps.vars.outputs.tag }} build/*
